### ISSUE TITLE
Flagged as malicious

### ISSUE THREAD

**Issue by pmcfarland** [sandwichdoge/MinimizeToTray#14]
I wanted to let you know that your tool is coming up as malicious for several vendors. Now I presume this is simply due to heuristics related to malicious apps trying to hide themselves and is therefor a false positive. I figured you would want to know and at least make some sort of declaration here or I see it's also on Softpedia.

https://www.virustotal.com/gui/file/82a8633c53e9f9106478b175490e8d215ddbf543b6ce76ef010955b0e71e78a7/detection 
![virustotal](https://user-images.githubusercontent.com/13721267/114771170-c9504d80-9d5b-11eb-8a9b-657a6d3f0134.png)

**Comment by sandwichdoge** [comment]
This issue is quite common with software written in AutoIt3. Because it's easy to whip up a standalone executable with AutoIt3, it's a popular language for hackers. An AutoIt3 executable packs the interpreter and the script file, if an Antivirus program flags the interpreter's signature, all programs compiled using AutoIt3 are affected as well.
