### ISSUE TITLE
Key remappings don't persist after reboots

### ISSUE THREAD

**Issue by sydbarrett74** [sandwichdoge/MinimizeToTray#23]
I've remapped the min/max key sequences to Alt + [Down Arrow] and Alt + [Up Arrow] in the config, but my alteration doesn't survive reboots. I have to do this remapping every time I restart my device. Do I need to run MTT as  Admin to make the remap persist?

I'm running Windows 11 23H2.

BTW, I love the simplicity of this app. Other than this reported issue, MTT Just Works(tm), and beautifully, at that. :)

**Comment by sandwichdoge** [comment]
MTT saves your config in MTTconf.ini file in the same directory as the exe. Make sure it has write permission to the directory in order to save the config file.

**Comment by sydbarrett74** [comment]
Would you allow me to do a PR to save these config settings to `%APPDATA%\MinimizeToTray` or should i fork?

**Comment by sandwichdoge** [comment]
Sure. But could you try saving in the program dir first before trying %APPDATA%, in that priority? This should apply to both loading and saving configs operations.

The reason is that MTT is a standalone binary and doesn't have an uninstaller so I'm averse to leaving garbage in the user's system. And the new version should also be back-compatible with the users' existing configs.
